name: Deploy to aws lambda using serverless framework
on:
  push:
    branches:
      - master
jobs:
  build:
    name:  Deploy aws lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        working-directory: ./backend
        run:
          |
          npm install
          npm install serverless -g
      - name: Serverless deploy
        uses: serverless/github-action@v2
        with:
          args: -c "cd ./backend && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SERVERLESS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SERVERLESS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SEND_TO: ${{ secrets.SEND_TO}}
          CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME}}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN}}
          HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME}}



